name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      stack_name:
        description: CloudFormation stack name
        required: true
      name:
        description: EC2 instance name
        required: true

env:
  STACK_NAME: ${{ inputs.stack_name }}
  NAME: ${{ inputs.name }}
  TEMPLATE_PATH: "iac/template.yml"
        
jobs:
  deploy:
    name: Github Actions Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Deploy IaC to AWS
      id: deploy-lambda
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ env.STACK_NAME }}
        template: ${{ env.TEMPLATE_PATH }}
        parameter-overrides: |
          Name=${{ env.NAME }}
        no-fail-on-empty-changeset: "1"
        capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND,CAPABILITY_NAMED_IAM